### ISSUE TITLE
💬 [Question] Documentation

### ISSUE THREAD

**Issue by darkdragon-001** [bundestag/gesetze-tools#41]
## :speech_balloon: Question
What type of documentation is needed? Currently, there is https://github.com/bundestag/gesetze-docs, which is mostly empty.

I suggest to keep things simple and add documentation in form of a `README.md` (and optionally a docs folder) to the corresponding repositories. This could then be parsed by https://readthedocs.org/ or similar. This way documentation is versioned together with the code.

Therefore I suggest to delete the gesetze-docs repository for now. @ulfgebhardt do you agree?

**Comment by ulfgebhardt** [comment]
Oh I did not know about https://github.com/bundestag/gesetze-docs - I will archive that repo - think thats a more non-intrusive way of handling things.

I generally think that documentation should be close to the code - those things should not be separated. I agree on the `README.md` and the `docs/`. More important then docs are automatic outputs in my opinion. If we have a working scraper the common dev should be informed how to operate it and what are system requirements to get things running.
The common muggel has to be informed where he can find the automatically generated output.

**Comment by darkdragon-001** [comment]
The the repo only contains placeholders and no content at all, I suggested deletion but would be fine with archival as well.

Please close this issue once it's done.

**Comment by ulfgebhardt** [comment]
![image](https://user-images.githubusercontent.com/1238238/115141784-6d791380-a03e-11eb-9b20-969ace805fc3.png)
