### ISSUE TITLE
suggestion for lawde.py

### ISSUE THREAD

**Issue by ousia** [bundestag/gesetze-tools#6]
Many thanks for your excellent initative.

Would it be possible that it could be used only to donwload other formats such as PDF or ePub? (Actually, I'm especially interested in ePub.)

Many thanks for your help,

Pablo

**Comment by darkdragon-001** [comment]
Unfortunately, this is out of scope for this repository.

However, you can easily do this yourself: `http://www.gesetze-im-internet.de/<slug>/<abbreviation>.pdf` for all entries in `data/laws.json` after running `lawde.py updatelist`.
